<?php
/**
 * Copyright 2025 (c) mediarox UG (haftungsbeschraenkt) (http://www.mediarox.de)
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Catalog\ProductShare\Block\Catalog\Product\View\Share as Block;
use Magento\Framework\Escaper;
use Catalog\ProductShare\Helper\Share as Helper;

/**
 * @var Block $block
 * @var Escaper $escaper
 * @var Helper $helper
 */
$helper = $this->helper(Helper::class);
$productUrl = $block->getProduct()->getProductUrl();
$productUrlEncoded = $block->getProductUrlEncoded();
$emailSubject = $block->getEmailSubject();
$productNameEmail = $block->getProductNameForEmail();
$productNameWhatsApp = $block->getProductNameForWhatsApp();

?>
<?php if ($helper->isEnabled()) : ?>
    <a href="#"
       class="action share"
       data-trigger="share-product"><span><?= $block->escapeHtml(__('Share')) ?></span></a>
    <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': '<?= $block->escapeHtml(__('Share product')) ?>',
            'trigger': '[data-trigger=share-product]',
            'responsive': true,
            'buttons': []
        }}">
        <div class="content">
            <ul>
                <li><a href="javascript:navigator.clipboard.writeText('<?= $productUrl ?>')"><?= __('Copy link') ?></a></li>
                <li><a href="https://api.whatsapp.com/send/?text=<?= $productNameWhatsApp ?>+-+<?= $productUrlEncoded ?>&type=custom_url&app_absent=0"><?= __('WhatsApp') ?></a></li>
                <li><a href="mailto:?subject=<?= $emailSubject ?>&body=<?= $productNameEmail ?>%20-%20<?= $productUrl ?>"><?= __('E-Mail') ?></a></li>
            </ul>
            
        </div>
    </div>
<?php endif; ?>